// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_index_version.test.ts.

/** The version of the `@ggdna/dna-index` package. */
export const dnaIndexVersion = '0.1.2';
